export default [
  { path: '/', redirect: '/home' },
  { path: '/home', name: '首页', icon: 'dashboard', component: './Home' },
  { path: '/manager', name: '账号管理', icon: 'user', component: './Manager' },
  { path: '/textbook', name: '教材管理', icon: 'book', component: './Textbook/List' },
  { path: '/textbook/detail/:id', component: './Textbook/Detail' },
  { path: '/question', name: '题目管理', icon: 'question', component: './Question/List' },
  { path: '/question/edit/:id', component: './Question/Edit' },
  { path: '/question/detail/:id', component: './Question/Detail' },
  { path: '/student', name: '学生管理', icon: 'Github', component: './Student/List' },
  { path: '/student/detail/:id', component: './Student/Detail' },
  { path: '/student/:id/practice-history', component: './Student/PracticeHistory' },
  { path: '/student/:id/practice/:type/:sessionId', component: './Student/PracticeDetail' },
  { path: '/task', name: '任务管理', icon: 'ClockCircle', component: './Task/List' },
  { path: '/task/detail/:id', component: './Task/Detail' },
  { path: '/password', component: './ModifyPassword' },
  { path: '/login', layout: false, component: './Login' },
  { path: '*', layout: false, component: './404' },
];
