[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
asyncio_default_fixture_loop_scope = function
log_cli = true
log_cli_level = INFO
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
